### ISSUE TITLE
Guild Colors and OOC Color is Broken.

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#110]
The colors don't show up despite being set correctly in the guild settings.

![image](https://user-images.githubusercontent.com/7554516/83312716-5e4c6580-a1e1-11ea-8b40-097f83fb3701.png)
![image](https://user-images.githubusercontent.com/7554516/83312805-bbe0b200-a1e1-11ea-8d6b-39921abd16e3.png)

**Comment by maartenl** [comment]
Hello, there! Yes, Angular will remove css styling that is inserted directly. That's because it might interfere with the custom css that Angular is using (bootstrap).

### Solution
So, in order for me to fix it, I shall add the styling classes you need to the app. Unfortunately, I will need a list of all the possible colours you want to have in there. (name and #colorcode would be ideal)
something like:
purple=#9767e0
blue=#etc
green=#etc

I know it's not as flexible as it used to be, but it's a small price for security and overal style.

### Some small notes from the screenshots:
- don't use &lt;font color="stuff"&gt;, The &lt;font&gt; tag has been removed in HTML5.
- things like &lt;span style="text-decoration etc. etc. etc"&gt; doesn't work. Angular removes the style attribute.

### Temporary workaround
So, if you wish to have something you like (without me having to change anything), you can try the following:
- surf to bootstrap website https://getbootstrap.com/docs/4.0
- under "Utilities", lookup "Colors"
- You see a bunch of css classes available. Pick one you like.
- Apply as described: for example in your screenshot above &lt;p class="text-success"&gt;&lt;b&gt;&lt;u&gt;ANNOUNCEMENTS&lt;/u&gt;&lt;/b&gt;&lt;/p&gt;
- added benefit, these classes will automatically change, when you switch over to Darkmode.

**Comment by wastedshame** [comment]
chocolate #D2691E
cornflowerblue #6495ED
red #FF0000
darkcyan #008B8B
darkgoldenrod #B8860B
darkorange #FF8C00
darkorchid #9932CC
deeppink #FF1493
deepskyblue#00BFFF
dodgerblue #1E90FF
forestgreen #228B22
fuchsia #FF00FF
gold #FFD700
goldenrod #DAA520
hotpink #FF69B4
indianred #CD5C5C
lightcoral #F08080
lightseagreen #20B2AA
lime #00FF00
limegreen #32CD32
mediumorchid #BA55D3
mediumpurple #9370DB
mediumslateblue #7B68EE
mediumvioletred #C71585
olive #808000
olivedrab #6B8E23
orangered #FF4500
orchid #DA70D6
palevioletred #DB7093
peru #CD853F
royalblue #4169E1
seagreen  #2E8B57
sienna #A0522D
steelblue #4682B4
teal #008080

List of possibly "custom colors" being used by current guilds (yes I went down the list and copied them):
#d55b18
#52a541
#057e66
#bd8500
#754719
#990033
#778899
#9767e0
#03b37b
#006699
#cc6699
#5b7bb7
#8B4513
#82a237
#cc9900
