### ISSUE TITLE
Websocket Fails within 1-2 minutes since cloud

### ISSUE THREAD

**Issue by nickicolem** [maartenl/Land-of-Karchan#139]
Since the update today of going to the cloud, the websocket fails within 1 to 2 minutes.  Have tried edge, chrome, avg secure browser and firefox. Cookies etc cleared and did not fix.

**Comment by wastedshame** [comment]
This has become a high priority issue. In order to get anything to show up, I have to hit refresh every single time I do anything, including testing commands I'm programming to see if they are working correctly.
It's very frustrating from an admin point of view, so it must be infuriating for the players.
I know you said you would look into it soon, but I thought I would add my two cents.

**Comment by maartenl** [comment]
I'm going to assume the problem has dissipated. 

Are there still people with this problem? I'll get something going so you can easily reattach the websocket if it breaks.
