### ISSUE TITLE
**MAJOR: Adding Attributes Not Working In Game

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#213]
We've been using the commands 'xattribute' and 'xremattribute' to add and remove attributes.

The first one does not work, and it is set up to set any attribute we want by typing dub name (attribute), ex: dub Victoria deputy.
The command 'undub name (attribute)' still works, as I tested it on my wife's character, and it is not that much different. Ex: undub Almahvius canijoin.

I tested a popular command meant to add a specific attribute as well, and it appears that the attribute did not work for this either.

This is a major bug for us.

I should note that the attributes can be added through the admin pages, but that isn't enough. 

If you require any further testing, please let me know.

**Comment by maartenl** [comment]
What error message do you get? (error messages can also be viewed in karchanadmin app, Systemlog.)

**Comment by wastedshame** [comment]
![Screenshot_20221207-082755](https://user-images.githubusercontent.com/7554516/206191757-73b23508-d2ff-4776-bae8-eb34eebfda10.png)
![Screenshot_20221207-082805](https://user-images.githubusercontent.com/7554516/206191783-be0da1c2-c3d0-4c0f-af71-d070cc41669e.png)
![Screenshot_20221207-082816](https://user-images.githubusercontent.com/7554516/206191800-43e27214-08d1-40a0-8571-8228eaf8c847.png)

**Comment by wastedshame** [comment]
I should add that in game, there is no error message. It just doesn't add the attribute and the command entered to add it doesn't get removed from the submit bar.

**Comment by maartenl** [comment]
The method signature is:
public void setAttribute(String name, String value)

The value should be a string. Try "true" instead of true.

I'm very sorry for all this, but the upgrade from Java 11 to Java 17, causes the Javascript engine Nashorn we use to be removed. I've replaced it with the one from GraalVM, but it is more strict in how it handles calls between JavaScript (no typing) to Java (static typing).

Expect more problems.

But leave this one open -> we should have proper error messages to the user, so there's something wrong there.
