### ISSUE TITLE
Character Sheets

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#28]
Whenever you go to your character sheet in game, it erases your storyline. I discovered this today when I noticed that my character Cascade's storyline had disappeared, much to my chagrin because I worked hard on it.

**Comment by maartenl** [comment]
I just edited my storyline, and it is saved properly. I used Linux/Firefox as Browser. Can you verify that this problem occurs for a specific browser, or for all browsers?

**Comment by wastedshame** [comment]
I've found that this usually happens if I have to edit my title, that and I use a lot of html to spruce up my character sheets when I make them. I don't know if that has anything to do with it or not. (As an example, look at Lillian's character sheet.)
Sorry for slow response. Just not got online.
-Nettie *~~~~~~~~~~*~~~~~~~~~~*~~~~~~~~~~*
“With the world always filling you, no one has to worry about what's in your mind. With everyone's imagination atrophied, no one will ever be a threat to the world.” 
  Chuck Palahniuk, Lullaby

**Comment by maartenl** [comment]
I wish to know if this is still the case with the new interface. Can you confirm?

**Comment by nickicolem** [comment]
I think it is fine, the issue was happening when we were having to change our title via settings rather than the title command.

I have tested character sheets and adding stories, seems to work fine for me.

I can remove relations but not add them though. I don't think that is really too much of a big issue? Also I use safari and chrome for iPad so perhaps a dep who uses a computer might want to inc this on their test of it?

**Comment by maartenl** [comment]
All righty then, closing this issue.

I did verify that now the adding of relations works like it should.
