### ISSUE TITLE
Bigtalk

### ISSUE THREAD

**Issue by nickicolem** [maartenl/Land-of-Karchan#37]
Bigtalk is glitchy. I don't use it myself so can't elaborate.

**Comment by maartenl** [comment]
I'm trying to re-introduce bigtalk, and I need some information.

Basically, there's two ways I can go about it:

1. add a big "textarea" field that can be toggled on and off using the BigTalk button, where you can write big pieces of html-enabled text
2. create a HTML editor component that is toggled on and off using the BigTalk button, where you CANNOT write HTML, but the editor offers you all you need.

For an example of point 2, I'm currently looking at CKEditor 5, Classic build, available at https://ckeditor.com/ckeditor-5/demo/

**Comment by wastedshame** [comment]
Haven't been around much today or I would have responded sooner.

I had a small work around for big talk for awhile that generated a textarea that people could size how they wanted, but people didn't use it except me because they wanted to be able to hit submit to send their posts instead of copy/pasting from my command's textarea to the actual submit bar, so I think based on that, moving away from textarea and to the editor you mentioned would be the best option.

**Comment by wastedshame** [comment]
If you're still testing, I thought I would give you an update with an image of what it looked like when I tried to use bigtalk today. 
![bigtalk](https://user-images.githubusercontent.com/7554516/55293677-e7da8a80-53c6-11e9-9953-4df1c4cfe168.jpg)

**Comment by maartenl** [comment]
Yes, I know. I failed to tell how it works. :(

The first box (the "normal"one) is for the command. The editor is for the rest, if you wish to put in something big.

So,...

You could try, in the first box:
"me attempts to post the following:"
and then the editor:
"### Now hear this! Now hear this!
etc..."
