### ISSUE TITLE
Character Pages in Admin Sheets

### ISSUE THREAD

**Issue by nickicolem** [maartenl/Land-of-Karchan#38]
Last Login Date
Creation Date 
Character Name Search
Characters to Bots/Shopkeepers
Removal of Title Change
Gender Change

**Comment by nickicolem** [comment]
Also the ability to see what attributes a char has. Also a way of seeing a list of what chars has a certain attribute.

**Comment by Midevia** [comment]
If we could also have a way to remove attributes from a character via the admin pages -- a way that is not tied to who owns the character, that would be awesome. At present we must design a command and attempt to catch the person in game if we'd like to see an attribute removed (say because they are no longer active within a guild and therefore no longer need access to any guild commands that atttribute might bring.)

**Comment by wastedshame** [comment]
I personally like being able to change titles. The only time I've used them was when I was moving one of my bots to a different area and needed to reflect the changes. Also, it helps with inappropriate titles when we don't want to kick. I also update my own banners in admin sometimes if I don't feel like logging the character in. The rest I agree with.
