### ISSUE TITLE
Guild Problems

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#52]
We cannot create new guilds.
Guild bosses can only accept, reject, and boot people for guilds. They cannot make or change ranks.

**Comment by wastedshame** [comment]
Also, they cannot delete ranks.

**Comment by wastedshame** [comment]
Just a quick question.I noticed that you closed the thread and have fixed things, but I was curious if the commands changed? The commands we had before don't seem to be working. Can you let us know what the changes are, if any? Thanks. :)
-Nettie/Victoria
 *~~~~~~~~~~*~~~~~~~~~~*~~~~~~~~~~*
“Once you've arrived at the end of the world, it hardly matters which route you took.” 
 Isaac Marion, Warm Bodies

**Comment by wastedshame** [comment]
Great job!
I tested all of the commands out and everything seems to be in working order except guilddelrank. I can create and assign just fine, but deleting a rank isn't working for me.
Can also update old ranks.
One other thing of note, is that new ranks are only able to be one word long. For guilds with more complicated ranks, this could prove detrimental. For example, CPDC has shields for the paladins, like Shield of Treachery, Shield of Wrath, Shield of Pride, etc.
The Knights have Shield of Faith, Shield of Temperance, Shield of Consistency.

I appreciate all of the work you've been doing. Guilds are going swimmingly! I just thought I'd leave a small note with my findings in case you were interested. Thank you so much for working on this!

**Comment by maartenl** [comment]
This issue is now closed. If you have additional problems/wishes, kindly open up a new issue for each problem/wish. That way I can keep changes in my code aligned with issues.

Also, if there are problems, please be as specific as possible. You are trying to delete a rank. Which rank, of which guild are you trying to delete? Which command did you use? Who were you logged in as at the time? And what error message did you get?

Then I can retry the same situation at home, and see what's wrong.
