### ISSUE TITLE
Request for Sleep

### ISSUE THREAD

**Issue by wastedshame** [maartenl/Land-of-Karchan#55]
I think it would be a good idea if we had some options like Hollow has, where you can set your status and it shows up on the who list beside your banner. I know we have the sleep function, but no one uses it because they don't see a good reason.

https://www.hollowgame.com/game/who-is-online

If we had options like that where we could easily set our status to show what we're doing, I think it would encourage people to seek each other out and also keep down (mild) drama when people are just lurking.

No rush, but this would be nice to have in game.

**Comment by Midevia** [comment]
As someone who actively plays both games...This is not really a feature I would like to see in Karchan. If it is implemented, I would hope it is low priority. Most of my rp in Hollow is actually found by speaking on the ooc. 'Hey rp anyone?'  We can be better about creating plots of substance and participating in group RPs rather than having to have those one-on-one RPs all the time. 

The mild drama with people lurking could be avoided if player a can actually respect when player b is just lurking -- as they are often told such -- and when they are told you know...be polite and stop posting at the lurker. 

I don't want to be the Hollow knock off by taking all of their unique features. :-/

**Comment by wastedshame** [comment]
Okay, what about changing Sleep from sleep to AFK or BRB? That would be simple and make more sense.

My issue with lurkers is that, sometimes, they do NOT tell people they are just lurking, so people with good intentions that try to rp with them sometimes get snapped at. This happens more than it should, which is why I like the possibility of a lurking option.

I'm open to suggestions if you have something better to propose? My main issue for bringing this up is I get tired of hearing 'so and so snapped at me because I tried to rp with them'!

**Comment by nickicolem** [comment]
perhaps we close this and discuss as a dep group discussion first?

**Comment by maartenl** [comment]
Any news on this?

**Comment by nickicolem** [comment]
Will instigate a dep convo and get back to you. Should hopefully have response in the next week.

**Comment by nickicolem** [comment]
Okay this is good to be closed. It isn't something at this moment in time it looks like we want to go go for. thanks though.

**Comment by maartenl** [comment]
Closing...
